apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: '556095356826.dkr.ecr.ap-south-1.amazonaws.com/mtp-repo:latest'
          ports:
            - containerPort: 9090

---

apiVersion: v1
kind: Service
metadata:
  name: admin-service
  labels:
    name: admin
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: admin
  type: LoadBalancer